version: 2

sources:
  - name: bronze
    description: Esta é uma replica do BD produção TOTVS
    tables:
      - name: SA1010
        description: Esta é a tabela de clientes
        columns:
          - name: "A1_COD"
            description: Esta coluna identifica o codigo do cliente
          - name: "A1_LOJA"
            description: Esta coluna identifica a loja do cliente
          - name: "A1_NOME"
            description: Esta coluna identifica o nome do cliente
          - name: "A1_EST"
            description: Esta coluna identifica a união federativa do cliente
          - name: "A1_MUN"
            description: Esta coluna identifica o municipio do cliente
          - name: "A1_CGC"
            description: Esta coluna identifica o CPF/CNPJ do cliente
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: SB1010
        description: Esta é a tabela de produtos
        columns:
          - name: "B1_COD"
            description: esta coluna identifica o codigo do produto
          - name: "B1_ZBM"
            description: esta coluna identifica o codigo do subgrupo do produto
          - name: "B1_DESC"
            description: esta coluna identifica a descricao (nome) do produto
          - name: "D_E_L_E_T_" 
            description: verifica se o registro esta deletado (deleção logica)
          - name: "B1_FILIAL"
            description: esta coluna identifica a filial do produto
      - name: SA3010
        description: Esta é a tabela de vendedor
        columns:
          - name: "A3_COD"
            description: esta coluna identifica o codigo do vendedor
          - name: "A3_NOME"
            description: esta coluna identifica o nome do vendedor
          - name: "A3_EST"
            description: esta coluna identifica a uniao federativa do vendedor
          - name: "A3_MUN"
            description: esta coluna identifica o municipio do vendedor
          - name: "A3_TIPO"
            description: esta coluna identifica o tipo do vendedor (Interno, Externo ...)
          - name: "A3_GERENC"
            description: esta coluna identifica o gerente do vendedor
          - name: "A3_ADMISS"
            description: esta coluna identifica a data de admissao do vendedor
          - name: "A3_MSBLQL"
            description: esta coluna identifica se o vendedor esta bloqueado
          - name: "A3_NOMSUP"
            description: esta coluna identifica o nome supervisor do vendedor
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: SA4010
        description: Esta é a tabela de transportadora
        columns:
          - name: "A4_COD"
            description: esta coluna identifica o codigo da transportadora
          - name: "A4_NOME"
            description: esta coluna identifica o nome da transportadora
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: ZBM010
        description: Esta é a tabela de subgrupo do produto (personalizada)
        columns:
          - name: "ZBM_COD"
            description: esta coluna identifica o codigo do subgrupo
          - name: "ZBM_DESC"
            description: esta coluna identifica o nome do subgrupo
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: SC5010
        description: Esta é a tabela de pedidos (cabeçalho)
        columns:
          - name: "C5_EMISSAO"
            description: esta coluna identifica a data de emissao do pedido
          - name: "C5_CONDPAG"
            description: esta coluna identifica a condição de pagamento do pedido
          - name: "C5_VEND1"
            description: esta coluna identifica a vendedor do pedido (nesse caso o representante comercial)
          - name: "C5_VEND2"
            description: esta coluna identifica a vendedor interno do pedido (nesse caso o apoio de venda comercial)
          - name: "C5_VEND3"
            description: esta coluna identifica a vendedor interno do pedido (nesse caso o apoio de venda de peças comercial)
          - name: "C5_TPFRETE"
            description: esta coluna identifica o tipo de frete do pedido
          - name: "C5_ZFSAIDA"
            description: esta coluna identifica data de saida do pedido
          - name: "C5_ZMENSPD"
            description: esta coluna identifica a mensagem (observação) do pedido
          - name: "C5_ZFRETEC"
            description: esta coluna identifica o valor de frete do pedido 
          - name: "C5_TRANSP"
            description: esta coluna identifica o codigo da transportadora do pedido
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
          - name: "C5_NOTA"
            description: esta é a coluna da NF do pedido
      - name: SC6010
        description: Esta é a tabela de pedidos (itens do pedido)
        columns:
          - name: "C6_PRODUTO"
            description: esta coluna identifica o codigo do produto do pedido
          - name: "C6_NOTA"
            description: esta coluna identifica nota fiscal do produto do pedido
          - name: "C6_DATFAT"
            description: esta coluna identifica data de faturamento do produto do pedido
          - name: "C6_NUM"
            description: esta coluna identifica o numero do pedido
          - name: "C6_LOCAL"
            description: esta coluna identifica o armazem (estoque) que o produto saiu
          - name: "C6_QTDVEN"
            description: esta coluna identifica a quantidade do produto do pedido
          - name: "C6_ITEM"
            description: esta coluna identifica qual o item do produto do pedido
          - name: "C6_QTDENT"
            description: esta coluna identifica a quantidade do produto entregue (entrega parcial)
          - name: "C6_PRCVEN"
            description: esta coluna identifica o preço de venda do produto do pedido
          - name: "C6_VALOR"
            description: essa coluna identifica o valor total do produto (C6_PRCVEN * C6_QTDVEN)
          - name: "C6_CLI"
            description: essa coluna identifica o codigo do cliente
          - name: "C6_LOJA"
            description: essa coluna identifica a loja do cliente 
          - name: "C6_BLQ"
            description: essa coluna identifica o status do pedido
          - name: "C6_FILIAL"
            description: essa coluna identifica a filial do cliente
          - name: "C6_TES"
            description: essa coluna identifica o tipo de saida do item
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: SF4010
        description: esta é a tabela de tipos de doc de entrada e saida
        columns:
          - name: "F4_CODIGO"
            description: essa coluna identifica o codigo do doc
          - name: "F4_DUPLIC"
            description: essa coluna identifica se houve duplicata ou nao
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: DB3010
        description: esta é a tabela de itens do doc de recebimento
        columns:
          - name: "DB3_CODPRO"
            description: ""
          - name: "DB3_QTDAPR"
            description: ""
          - name: "DB3_NRAVRC"
            description: ""
          - name: "DB3_ITEM"
            description: ""
          - name: "DB3_DTVALD"
            description: ""
          - name: "DB3_CERTIF"
            description: ""
          - name: "DB3_NUMPC"
            description: ""
          - name: "DB3_ITEMPC"
            description: ""
          - name: "DB3_QUANT"
            description: ""
          - name: "DB3_NRAVRC"
            description: ""
          - name: "D_E_L_E_T_"
            description: verifica se o registro esta deletado (deleção logica)
      - name: DB1010
        description: esta é a tabela de Aviso de Recebimento de Carga
        columns:
          - name: "DB1_MANIFE"
            description: ""
          - name: "DB1_ENTREG"
            description: ""
          - name: "DB1_HORA1"
            description: ""
          - name: "DB1_NRAVRC"
            description: ""
          - name: "D_E_L_E_T_"
            description: ""
      - name: DB2010
        descritpion: esta é a tabela de Cabecalho Doc de Recebimento
        columns:
          - name: "DB2_DOC"
            description: ""
          - name: "DB2_CLIFOR"
            description: ""
          - name: "DB2_LOJA"
            description: ""
          - name: "DB2_EMISSA"
            description: "" 
          - name: "DB2_CRACHA"
            description: ""
          - name: "DB2_FILIAL"
            description: ""
          - name: "DB2_NRAVRC"
            description: ""
          - name: "D_E_L_E_T_"
            description: ""
      - name: SC7010
        description: esta é a tabela de Pedido de Compra / Aut.Entrega
        columns:
          - name: "C7_NUM"
            description: ""
          - name: "C7_EMISSAO"
            description: ""  
          - name: "C7_FILIAL"
            description: ""
          - name: "C7_ITEM"
            description: ""
          - name: "C7_PRODUTO"
            description: ""
          - name: "C7_UM"
            description: ""
          - name: "C7_QUANT"
            description: ""
          - name: "C7_PRECO"
            description: ""
          - name: "C7_TOTAL"
            description: ""
          - name: "C7_IPI"
            description: ""
          - name: "C7_DATPRF"
            description: ""
          - name: "D_E_L_E_T_"
            description: ""
      - name: funcionario
        description: ""
        columns: 
          - name: cartao
          - name: funcionario
          - name: funcao
      - name: cert_status
        description: ""
        columns: 
          - name: diretorio_arquivo
          - name: uf
          - name: cod_fornecedor
          - name: loja
          - name: fornecedor
          - name: genero_cert
          - name: nome_arquivo
          - name: validade_cert
      - name: SA2010
        description: ""
        columns: 
          - name: "A2_COD"
          - name: "A2_NOME"
          - name: "A2_NREDUZ"
          - name: "A2_LOJA"
          - name: "A2_CGC"
          - name: "A2_FILIAL"
          - name: "D_E_L_E_T_"
      - name: CTT010
        description: "Esta é a tabela de centro de custo"
        columns: 
          - name: "CTT_CUSTO"
          - name: "CTT_DESC01"
          - name: "D_E_L_E_T_"
      - name: QI2010
        description: "Esta é a tabela de não conformidade"
        columns: 
          - name: "QI2_ZRFNC"
          - name: "QI2_REV"
          - name: "QI2_TPFIC"
          - name: "QI2_PRIORI"
          - name: "QI2_STATUS"
          - name: "QI2_CODPRO"
          - name: "QI2_LOJCLI"
          - name: "QI2_CODCLI"
          - name: "QI2_ZZSERI"
          - name: "QI2_ZZGAR"
          - name: "QI2_ZZTPAT"
          - name: "QI2_ZZ0S"
          - name: "QI2_CODORI"
          - name: "QI2_DDETA"
          - name: "QI2_CODEFE"
          - name: "QI2_CODCAT"
          - name: "QI2_CODACA"
          - name: "QI2_MAT"
          - name: "QI2_REGIST"
          - name: "QI2_CONREA"
          - name: "QI2_CONTAT"
          - name: "QI2_FONE"
          - name: "QI2_ZZKM"
          - name: "QI2_ZZVMO"
          - name: "QI2_ZZVOD"
          - name: "QI2_ZZDPMO"
      - name: QAA010
        description: "Esta é a tabela de usuario do modulo de nao conformidade"
        columns:
          - name: "QAA_MAT"
          - name: "QAA_NOME"
          - name: "QAA_APELID"
          - name: "D_E_L_E_T_"
      - name: QI0010
        description: "Esta é a tabela de classificação de efeito, categoria e origem de nao conformidade"
        columns:
          - name: "QI0_CODIGO"
          - name: "QI0_DESC"
          - name: "D_E_L_E_T_"
      - name: ZQ1010
        description: "Esta é a tabela de garantias usada no relatorio de não conformidade"
        columns:
          - name: "ZQ1_FNC"
          - name: "ZQ1_ITEM"
          - name: "ZQ1_QTDE"
          - name: "D_E_L_E_T_"
          - name: "ZQ1_TPITEM"
      - name: SF2010
        description: Esta é a tabela de NF de saida
        columns:
          - name: "F2_DOC"
          - name: "F2_EMISSAO"
          - name: "F2_EST"
          - name: "F2_CLIENTE"
          - name: "F2_LOJA"
          - name: "F2_DUPL"
          - name: "F2_TIPO"
          - name: "D_E_L_E_T_"
      - name: SD2010
        description: Esta é a tabela de itens da NF de saida
        columns:
          - name: "D2_DOC"
          - name: "D2_COD"
          - name: "D2_CF"
          - name: "D2_QUANT"
          - name: "D2_TOTAL"
          - name: "D2_VALIPI"
          - name: "D2_ICMSRET"
          - name: "D2_SEGURO"
          - name: "D2_VALFRE"
          - name: "D2_DESPESA"
          - name: "D2_TES"
          - name: "D_E_L_E_T_"
      - name: dna
        description: "Esta é a tabela de garantias usada no relatorio de não conformidade"
        columns:
          - name: "MUNICÍPIO BASE IBGE"
          - name: "MUN. Alterar"
          - name: "MESOREGIÃO IBGE"
          - name: "uf"
          - name: "Nº HABIT. REP."
          - name: "RENDA PERCAPITA"
          - name: "potencial"

      